<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="dibanescu" lastModifiedBy="dibanescu" checksumTest="true" creationDate="20/10/2016 15:58:39 +0300" engineType="DML" lastModifiedDate="20/10/2016 15:58:54 +0300" engineVersion="2.1">
   <mappingInformations>
      <mappingInformation state="Inactive" path="Mapping Flows/edi.dmlflw"/>
   </mappingInformations>
</project>