<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="dibanescu" lastModifiedBy="dibanescu" checksumTest="true" creationDate="20/10/2016 15:05:38 +0300" engineType="DML" lastModifiedDate="20/10/2016 15:05:57 +0300" engineVersion="2.1">
   <mappingInformations>
      <mappingInformation state="Inactive" path="Mapping Flows/edifact.dmlflw"/>
   </mappingInformations>
</project>