<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="dibanescu" lastModifiedBy="dibanescu" checksumTest="true" creationDate="18/10/2016 17:23:49 +0300" engineType="DML" lastModifiedDate="18/10/2016 17:24:17 +0300" engineVersion="2.1">
   <mappingInformations>
      <mappingInformation state="Inactive" path="Mapping Flows/flat_file.dmlflw"/>
   </mappingInformations>
</project>