<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="dibanescu" lastModifiedBy="dibanescu" checksumTest="true" creationDate="24/10/2016 12:08:56 +0300" engineType="DML" lastModifiedDate="24/10/2016 12:10:15 +0300" engineVersion="2.1">
   <mappingInformations>
      <mappingInformation state="Inactive" path="Mapping Flows/edifact.dmlflw"/>
   </mappingInformations>
</project>