<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="dibanescu" lastModifiedBy="imhurduc" checksumTest="true" creationDate="17/10/2016 16:32:34 +0300" engineType="DML" lastModifiedDate="19/10/2016 12:05:33 +0300" engineVersion="2.1">
   <mappingInformations>
      <mappingInformation state="Inactive" path="Mapping Flows/flatFile.dmlflw"/>
   </mappingInformations>
</project>