<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="dibanescu" encoding="UTF-8" lastModifiedBy="dibanescu" checksumTest="true" creationDate="20/10/2016 16:12:42 +0300" engineType="MB" lastModifiedDate="20/10/2016 16:13:41 +0300">
   <mappingInformations>
      <mappingInformation state="Inactive" path="Maps/datamapper_map.map">
         <flow factoryType="FlowAdapter" mapFileName="~/Maps/datamapper_map.map" codeFileName="Template: DMnormal.mc"/>
      </mappingInformation>
   </mappingInformations>
</project>